name: PR Size Checker

on: pull_request

env:
  SIZE_LIMIT: 2

jobs:
  check_pr_size:
    name: Check PR size doesn't break set limit
    runs-on: ubuntu-latest
    steps:
      - name: "Say hello"
        run: echo "Hello"
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get number of changed lines
        id: changed-lines
        uses: hestonhoffman/changed-lines@v1
      - name: Fail if number of lines changed exceeds ${{ env.SIZE_LIMIT }}
        env:
          # Map the GitHub output to a shell variable here
          CHANGED_LINES_DATA: ${{ steps.changed-lines.outputs.changed_lines }}
        run: |
          echo "DEBUG: The content of changed_lines is:"
          echo "$CHANGED_LINES_DATA"
          if [ ${{ steps.changed-lines.outputs.changed_lines }} -gt ${{ env.SIZE_LIMIT }} ]; then
            exit 1
          fi
