name: My First Workflow

on:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          variable: thisdoesntmatteribelieve

      - run: npm install

      - run: gulp build

      - uses: actions/upload-artifact@v4
        with:
          name: MyFirstPackage
          path: dest
