name: My First Workflow

on:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:
    inputs:
      input1:
        description: "Input 1"
        required: true
        default: "creu"
      input2:
        description: "Input 2"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4

      - run: npm install

      - run: gulp build

      - uses: actions/upload-artifact@v4
        with:
          name: MyFirstPackage
          path: dest
